Revert "Add automatic module names for all Dropwizard modules" (#5137)
The automatic module name causes issues when generating Javadoc during the release process.

Let's revert that particular change so we can get the first beta builds out of the door and take care of it when we have more time to take care of the issues.

`release/3.0.x`: https://github.com/dropwizard/dropwizard/runs/5875633807?check_suite_focus=true#step:4:3444
```text
Error:  Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.2:jar (attach-javadocs) on project dropwizard-jersey: MavenReportException: Error while generating Javadoc: 
Error:  Exit code: 1 - /home/runner/work/dropwizard/dropwizard/dropwizard-jersey/src/main/java/io/dropwizard/jersey/DropwizardResourceConfig.java:29: error: cannot find symbol
Error:  import javax.annotation.Nullable;
Error:                         ^
Error:    symbol:   class Nullable
Error:    location: package javax.annotation
[...]
Error:  Command line was: /usr/lib/jvm/temurin-11-jdk-amd64/bin/javadoc @options @packages
Error:  
Error:  Refer to the generated Javadoc files in '/home/runner/work/dropwizard/dropwizard/dropwizard-jersey/target/apidocs' dir.
```


`release/4.0.x`: https://github.com/dropwizard/dropwizard/runs/5875544966?check_suite_focus=true#step:4:10598
```text
Error:  Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.2:jar (attach-javadocs) on project dropwizard-testing: MavenReportException: Error while generating Javadoc: 
Error:  Exit code: 1 - /home/runner/work/dropwizard/dropwizard/dropwizard-testing/src/main/java/io/dropwizard/testing/common/DropwizardTestResourceConfig.java:22: error: cannot access ResourceConfig
Error:  class DropwizardTestResourceConfig extends DropwizardResourceConfig {
Error:  ^
Error:    class file for org.glassfish.jersey.server.ResourceConfig not found
Error:  /home/runner/work/dropwizard/dropwizard/dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardExtensionsSupport.java:8: error: package org.junit.platform.commons.util is not visible
Error:  import org.junit.platform.commons.util.ReflectionUtils;
Error:                                   ^
Error:    (package org.junit.platform.commons.util is declared in module org.junit.platform.commons, which does not export it to module io.dropwizard.testing)
Error:  
Error:  Command line was: /usr/lib/jvm/temurin-11-jdk-amd64/bin/javadoc @options @packages
```

This reverts commit da2b0540d58b5e8057d77c4b2cda5a19a241a92d.
Refs #2926
Refs #5136