Disable failing tests on Windows
* CustomRequestLogPatternIntegrationTest
* RequestLogPatternIntegrationTest

Example exception (shortened):

ERROR [2019-03-02 10:38:12,736] org.junit.jupiter.engine.execution.JupiterEngineExecutionContext: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.MethodExtensionContext@72bca894
java.io.IOException: Failed to delete temp directory C:\Users\appveyor\AppData\Local\Temp\1\junit6846106039914940147. The following paths could not be deleted (see suppressed exceptions for details): , example-new-app-not-additive.log, example-new-app.log, example.log
at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:206)
at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:167)
Suppressed: java.nio.file.DirectoryNotEmptyException: C:\Users\appveyor\AppData\Local\Temp\1\junit6846106039914940147
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:187)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:182)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:173)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:173)
	at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:165)
	... 44 common frames omitted
Suppressed: java.nio.file.FileSystemException: C:\Users\appveyor\AppData\Local\Temp\1\junit6846106039914940147\example.log: The process cannot access the file because it is being used by another process.