Do not print error message about class not found (#3616)
Only swallow NoClassDefFoundError or TypeNotPresentException if the
default implementation generated it, and do not print message to
standard error about it. Currently an error message appears whenever
Logback (specifically the logback-access dependency) is excluded, which
users should be able to do if they configuring logging externally.

Fixes #3615

(cherry picked from commit a1fd3eabd1c78357ff796a7bc0e8472abcf9ec44)